---
# role: ansible-role-git
# file: tasks/main.yml

- name: Import tasks for role ansible-role-git
  block:
    - name: "Set os_family dependent variables"
      include_vars: '{{ ansible_os_family }}.yml'

    - name: "Set distribution dependent variables"
      include_vars: "{{ item }}"
      vars:
        params:
          files:
            - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
            - '{{ ansible_distribution }}.yml'
            - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
            - '{{ ansible_os_family }}.yml'
          paths:
            - 'vars'
      loop: "{{ query('first_found', params) }}"

    - name: "Install packages for ansible-role-git"
      package:
        name: "{{ git_packages }}"
        state: present

    - name: "Make gnome-keyring-support"
      shell: set -o pipefail && sudo make
      args:
        chdir: "{{ git_keyring_helper_path }}/"
        creates: "{{ git_keyring_helper_path }}/{{ git_keyring_helper_file }}"
        executable: /bin/bash
      when: not ansible_distribution == 'RedHat'
        and git_keyring_helper_file | default('') | length > 0

    - name: "Set permissions for gnome-keyring-support"
      file:
        path: "{{ git_keyring_helper_path }}/{{ git_keyring_helper_file }}"
        mode: '755'
        modification_time: preserve
        access_time: preserve
      when: git_keyring_helper_file | default('') | length > 0

    - name: "Configure git system settings"
      become: false
      template:
        src: "etc/gitconfig.j2"
        dest: "/etc/gitconfig"
        mode: '644'
  when: git_role_enabled | bool
