---
# role: ansible-role-git
# file: tasks/tasks.yml

- name: Set os_family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Set distribution dependent variables
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

- name: Install packages for ansible-role-git
  package:
    name: "{{ git_packages }}"
    state: present

- name: Make gnome-keyring-support
  shell: set -o pipefail && sudo make
  args:
    chdir: "{{ git_keyring_helper_path }}/"
    creates: "{{ git_keyring_helper_path }}/{{ git_keyring_helper_file }}"
    executable: /bin/bash
  when: not ansible_distribution == 'RedHat'

- name: Set permissions for gnome-keyring-support
  file:
    path: "{{ git_keyring_helper_path }}/{{ git_keyring_helper_file }}"
    mode: '755'
    modification_time: preserve
    access_time: preserve

- name: Configure git for current user ({{ lookup('env','USER') }})
  become: False
  template:
    src: gitconfig.j2
    dest: "{{ ansible_env.PWD }}/.gitconfig"
    mode: '600'
